In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('Google-Playstore.csv')
df.head()

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10+,10.0,15,True,0.0,...,https://beniyizibyose.tk/#/,jean21101999@gmail.com,"Feb 26, 2020","Feb 26, 2020",Everyone,https://beniyizibyose.tk/projects/,False,False,False,2021-06-15 20:19:35
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,"5,000+",5000.0,7662,True,0.0,...,https://webserveis.netlify.app/,webserveis@gmail.com,"May 21, 2020","May 06, 2021",Everyone,https://dev4phones.wordpress.com/licencia-de-uso/,True,False,False,2021-06-15 20:19:35
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50+,50.0,58,True,0.0,...,NaN,vnacrewit@gmail.com,"Aug 9, 2019","Aug 19, 2019",Everyone,https://www.vietnamairlines.com/vn/en/terms-an...,False,False,False,2021-06-15 20:19:35
3,Smart City Trichy Public Service Vehicles 17UC...,cst.stJoseph.ug17ucs548,Communication,5.0,5.0,10+,10.0,19,True,0.0,...,http://www.climatesmarttech.com/,climatesmarttech2@gmail.com,"Sep 10, 2018","Oct 13, 2018",Everyone,NaN,True,False,False,2021-06-15 20:19:35
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100+,100.0,478,True,0.0,...,http://www.horodyski.com.pl,rmilekhorodyski@gmail.com,"Feb 21, 2020","Nov 12, 2018",Everyone,http://www.horodyski.com.pl,False,False,False,2021-06-15 20:19:35

In [5]:
df.shape

(2312944, 24)

1)Exploration

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2312944 entries, 0 to 2312943
Data columns (total 24 columns):
 #   Column             Dtype
---  ------             -----
 0   App Name           str
 1   App Id             str
 2   Category           str
 3   Rating             float64
 4   Rating Count       float64
 5   Installs           str
 6   Minimum Installs   float64
 7   Maximum Installs   int64
 8   Free               bool
 9   Price              float64
 10  Currency           str
 11  Size               str
 12  Minimum Android    str
 13  Developer Id       str
 14  Developer Website  str
 15  Developer Email    str
 16  Released           str
 17  Last Updated       str
 18  Content Rating     str
 19  Privacy Policy     str
 20  Ad Supported       bool
 21  In App Purchases   bool
 22  Editors Choice     bool
 23  Scraped Time       str
dtypes: bool(4), float64(4), int64(1), str(15)
memory usage: 875.1 MB

In [7]:
df.isnull().mean().round(2)*100

App Name              0.0
App Id                0.0
Category              0.0
Rating                1.0
Rating Count          1.0
Installs              0.0
Minimum Installs      0.0
Maximum Installs      0.0
Free                  0.0
Price                 0.0
Currency              0.0
Size                  0.0
Minimum Android       0.0
Developer Id          0.0
Developer Website    33.0
Developer Email       0.0
Released              3.0
Last Updated          0.0
Content Rating        0.0
Privacy Policy       18.0
Ad Supported          0.0
In App Purchases      0.0
Editors Choice        0.0
Scraped Time          0.0
dtype: float64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,Rating,Rating Count,Minimum Installs,Maximum Installs,Price
count,2.290061e+06,2.290061e+06,2.312837e+06,2.312944e+06,2.312944e+06
mean,2.203152e+00,2.864839e+03,1.834452e+05,3.202017e+05,1.034992e-01
std,2.106223e+00,2.121626e+05,1.513144e+07,2.355495e+07,2.633127e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,5.000000e+01,8.400000e+01,0.000000e+00
50%,2.900000e+00,6.000000e+00,5.000000e+02,6.950000e+02,0.000000e+00
75%,4.300000e+00,4.200000e+01,5.000000e+03,7.354000e+03,0.000000e+00
max,5.000000e+00,1.385576e+08,1.000000e+10,1.205763e+10,4.000000e+02

In [10]:
df.describe(include='object')

C:\Users\mohan\AppData\Local\Temp\ipykernel_6576\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,App Name,App Id,Category,Installs,Currency,Size,Minimum Android,Developer Id,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Scraped Time
count,2312939,2312944,2312944,2312837,2312809,2312748,2306414,2312911,1552109,2312913,2241891,2312944,2312944,1891991,2312944
unique,2177943,2312944,48,22,15,1657,154,758371,810440,950456,4158,3918,6,977743,67374
top,Tic Tac Toe,com.ishakwe.gakondo,Education,100+,USD,Varies with device,4.1 and up,Subsplash Inc,http://www.subsplash.com/,support@classplus.co,"Jun 16, 2020","Jun 10, 2021",Everyone,http://www.subsplash.com/legal/privacy,2021-06-16 06:31:44
freq,382,1,241090,443368,2311548,74777,604465,5422,7519,10345,2051,11186,2022089,7481,56

In [11]:
df.nunique().sort_values()

Free                       2
Ad Supported               2
Editors Choice             2
In App Purchases           2
Content Rating             6
Currency                  15
Minimum Installs          22
Installs                  22
Rating                    42
Category                  48
Minimum Android          154
Price                   1063
Size                    1657
Last Updated            3918
Released                4158
Rating Count           38482
Scraped Time           67374
Maximum Installs      251563
Developer Id          758371
Developer Website     810440
Developer Email       950456
Privacy Policy        977743
App Name             2177943
App Id               2312944
dtype: int64

-Here we can know "How many application installed by 10Million downloads & how many 10000 & each amount?

In [12]:
df['Installs'].value_counts().sort_values()

Installs
10,000,000,000+         1
5,000,000,000+         14
1,000,000,000+         55
500,000,000+           65
100,000,000+          549
50,000,000+           824
10,000,000+          6192
5,000,000+           6595
0+                  11566
500,000+            27012
1,000,000+          33650
1+                  65345
5+                  73772
50,000+             75359
100,000+           110257
5,000+             143593
50+                170465
500+               189077
10,000+            256723
10+                300156
1,000+             398199
100+               443368
Name: count, dtype: int64

To show all columns name

In [13]:
df.columns.tolist()

['App Name',
 'App Id',
 'Category',
 'Rating',
 'Rating Count',
 'Installs',
 'Minimum Installs',
 'Maximum Installs',
 'Free',
 'Price',
 'Currency',
 'Size',
 'Minimum Android',
 'Developer Id',
 'Developer Website',
 'Developer Email',
 'Released',
 'Last Updated',
 'Content Rating',
 'Privacy Policy',
 'Ad Supported',
 'In App Purchases',
 'Editors Choice',
 'Scraped Time']

2)Data cleaning

------Now we will remove the non nessesary columns from the data & adjust the datatypes .

In [14]:
df.head(2)

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10+,10.0,15,True,0.0,...,https://beniyizibyose.tk/#/,jean21101999@gmail.com,"Feb 26, 2020","Feb 26, 2020",Everyone,https://beniyizibyose.tk/projects/,False,False,False,2021-06-15 20:19:35
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,"5,000+",5000.0,7662,True,0.0,...,https://webserveis.netlify.app/,webserveis@gmail.com,"May 21, 2020","May 06, 2021",Everyone,https://dev4phones.wordpress.com/licencia-de-uso/,True,False,False,2021-06-15 20:19:35

To train the machine we need to categorize the apps success then drop the unnessecary columns 
We add a success column that when the count of downloads=500,000 download that means the application is success

In [15]:
df['success']=(df['Minimum Installs']>=500_000).astype(int)

In [16]:
df['success'].value_counts(normalize=True).round(2)*100

success
0    97.0
1     3.0
Name: proportion, dtype: float64

In [17]:
drop=['App Id','Developer Id','Developer Website','Developer Email','Scraped Time','Currency','Privacy Policy','Installs','Minimum Installs','Maximum Installs','Rating Count']
df=df.drop(columns=drop)

In [18]:
df.columns.tolist()

['App Name',
 'Category',
 'Rating',
 'Free',
 'Price',
 'Size',
 'Minimum Android',
 'Released',
 'Last Updated',
 'Content Rating',
 'Ad Supported',
 'In App Purchases',
 'Editors Choice',
 'success']

---We recognized that the size is a "STR" while it should be "Float"
---so we need to study values of this column

In [19]:
df['Size'].str[-1].value_counts()

Size
M    2201705
e      74777
k      36253
G         13
Name: count, dtype: int64

There are 4 differt suffex so we need to remove the suffix

In [20]:
def convert_size(s):
    if pd.isnull(s) or s == 'Varies with device':   
        return np.nan
    s = str(s).replace(',', '')                     
    if s.endswith('M'):                             
        return float(s[:-1])
    elif s.endswith('k'):                            
        return float(s[:-1]) / 1024
    elif s.endswith('G'):                           
        return float(s[:-1]) * 1024
    return np.nan

In [21]:
df['Size_MB'] = df['Size'].apply(convert_size)

In [22]:
df = df.drop(columns=['Size'])

In [23]:
df.head(1)

,App Name,Category,Rating,Free,Price,Minimum Android,Released,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice,success,Size_MB
0,Gakondo,Adventure,0.0,True,0.0,7.1 and up,"Feb 26, 2020","Feb 26, 2020",Everyone,False,False,False,0,10.0

--The following col. indicated the min. type of mobile to open the app

In [24]:
df['Minimum Android'].value_counts().head(15)

Minimum Android
4.1 and up            604465
5.0 and up            396998
4.4 and up            390311
4.0.3 and up          180482
4.0 and up            153441
4.2 and up            115973
6.0 and up             89928
2.3 and up             65577
5.1 and up             59287
Varies with device     46214
4.3 and up             41357
7.0 and up             34444
2.2 and up             23720
2.3.3 and up           21549
3.0 and up             17105
Name: count, dtype: int64

In [25]:
df['Min_Android'] = df['Minimum Android'].str.extract(r'(\d+\.?\d*)')[0].astype(float)
df[['Minimum Android', 'Min_Android']].sample(10)

        Minimum Android  Min_Android
859047       2.3 and up          2.3
270910       5.0 and up          5.0
876991       4.1 and up          4.1
831072     4.0.3 and up          4.0
631266       4.4 and up          4.4
749585       4.1 and up          4.1
1546796      5.0 and up          5.0
1120540      4.1 and up          4.1
1845510      5.1 and up          5.1
801382       4.1 and up          4.1

In [26]:
df=df.drop(columns=['Minimum Android'])

In [27]:
df.head(1)

,App Name,Category,Rating,Free,Price,Released,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice,success,Size_MB,Min_Android
0,Gakondo,Adventure,0.0,True,0.0,"Feb 26, 2020","Feb 26, 2020",Everyone,False,False,False,0,10.0,7.1

- Release & Last Updated are STR columns so we need to convert it to a date time

In [28]:
df['Released'] = pd.to_datetime(df['Released'], errors='coerce')
df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors='coerce')
df[['Released', 'Last Updated']].head()

    Released Last Updated
0 2020-02-26   2020-02-26
1 2020-05-21   2021-05-06
2 2019-08-09   2019-08-19
3 2018-09-10   2018-10-13
4 2020-02-21   2018-11-12

In [29]:
df['Released_Year'] = df['Released'].dt.year
df['Last_Updated_Year'] = df['Last Updated'].dt.year

In [30]:
df.head(1)

,App Name,Category,Rating,Free,Price,Released,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice,success,Size_MB,Min_Android,Released_Year,Last_Updated_Year
0,Gakondo,Adventure,0.0,True,0.0,2020-02-26,2020-02-26,Everyone,False,False,False,0,10.0,7.1,2020.0,2020

We need to check duplicates after cleaning

In [31]:
df.duplicated().sum()

np.int64(135)

In [32]:
df = df.drop_duplicates()

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.isnull().mean().round(3) * 100

App Name             0.0
Category             0.0
Rating               1.0
Free                 0.0
Price                0.0
Released             3.1
Last Updated         0.0
Content Rating       0.0
Ad Supported         0.0
In App Purchases     0.0
Editors Choice       0.0
success              0.0
Size_MB              3.2
Min_Android          2.3
Released_Year        3.1
Last_Updated_Year    0.0
dtype: float64

3)Data analysis

In [35]:
import plotly.express as px

In [36]:
#As the data is about 2 million rows so will take a sample
sample = df.sample(400000, random_state=42)

Q1: What percentage of apps are successful?

In [70]:
counts = df['success'].value_counts()
px.pie(values=counts.values, names=['Not Successful', 'Successful'], title='Successful vs Not Successful Apps')

Only 3.2% of apps  are successful, while 96.8% are not. The data is highly imbalanced.

Q2: What is the distribution of app sizes?

In [71]:
px.histogram(sample, x='Size_MB', nbins=50, title='App Size Distribution (MB)')

Most of the apps are small where there are a large sizes apps it is mostly a game app

Q3: Are there outliers in app sizes?

In [72]:
px.box(sample, x='Size_MB', title='App Size Boxplot')

In [73]:
Q1 = df['Size_MB'].quantile(0.25)
Q3 = df['Size_MB'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df['Size_MB'] < lower) | (df['Size_MB'] > upper)]
print("Lower:", lower, "| Upper:", upper)
print("Number of outliers:", len(outliers))

Lower: -25.25 | Upper: 55.150000000000006
Number of outliers: 154735

Using the IQR method, most apps are between 5 MB and 25 MB. Apps larger than 55 MB are outliers

Q4: Are bigger apps more successful?

In [83]:
size_group = pd.cut(df['Size_MB'], bins=[0, 10, 25, 55, 100, 5000],
                    labels=['<10 MB', '10-25 MB', '25-55 MB', '55-100 MB', '>100 MB'])
size_rate = (df.groupby(size_group, observed=True)['success'].mean() * 100).round(2)
px.bar(size_rate, text_auto=True, title='Success Rate % by App Size')

The large apps are more succissfull which is by logic is a wright thing as that means there are alot of features in the app so many people will download it

Q5: Are there outliers in prices of paid apps?

In [84]:
paid = df[df['Price'] > 0]
price_group = pd.cut(paid['Price'], bins=[0, 1, 2, 5, 10, 50, 500],
                     labels=['$0-1', '$1-2', '$2-5', '$5-10', '$10-50', '$50+'])
px.bar(price_group.value_counts().sort_index(), text_auto=True, title='Paid Apps by Price Range')

most apps are cheap about 5$

Q6: What are the top 10 categories by number of apps?

In [76]:
px.bar(df['Category'].value_counts().head(10), text_auto=True, title='Top 10 Categories by Number of Apps')

the largest category is the educational

Q7: Which categories have the highest success rate?

In [77]:
cat_rate = (df.groupby('Category')['success'].mean() * 100).round(2).sort_values(ascending=False).head(10)
px.bar(cat_rate, text_auto=True, title='Top 10 Categories by Success Rate %')

Q8: Do apps with in-app purchases succeed more?

In [85]:
iap_rate = (df.groupby('In App Purchases')['success'].mean() * 100).round(2)
px.bar(iap_rate, text_auto=True, title='Success Rate % by In-App Purchases')

Q9: Do apps with ads succeed more?

In [86]:
ads_rate = (df.groupby('Ad Supported')['success'].mean() * 100).round(2)
px.bar(ads_rate, text_auto=True, title='Success Rate % by Ad Support')

Q10: How did the number of apps and their success rate change over the years?

In [81]:
yearly = df.groupby('Released_Year')['success'].agg(['count', 'mean']).reset_index()
yearly['mean'] = yearly['mean'] * 100
px.line(yearly, x='Released_Year', y='count', markers=True, title='Number of Apps Released per Year')

In [82]:
px.line(yearly, x='Released_Year', y='mean', markers=True, title='Success Rate % by Release Year')

4)Data preparing for modeling

Here we start training & testing the module

In [48]:
df_model = df.drop(columns=['App Name', 'Released', 'Last Updated', 'Rating', 'Editors Choice'],
                   errors='ignore')
df_model.columns.tolist()

['Category',
 'Free',
 'Price',
 'Content Rating',
 'Ad Supported',
 'In App Purchases',
 'success',
 'Size_MB',
 'Min_Android',
 'Released_Year',
 'Last_Updated_Year']

In [49]:
df_model = df_model.sample(200000, random_state=42)
X = df_model.drop(columns=['success'])
y = df_model['success']
print(X.shape, y.shape)

(200000, 10) (200000,)

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

print("Train:", X_train.shape, "| Test:", X_test.shape)
print(y_train.mean(), y_test.mean())

Train: (160000, 10) | Test: (40000, 10)
0.0322625 0.032275

Pipe line stage

In [51]:
num_cols = ['Price', 'Size_MB', 'Min_Android', 'Released_Year', 'Last_Updated_Year']
cat_cols = ['Category', 'Content Rating']
bool_cols = ['Free', 'Ad Supported', 'In App Purchases']

In [52]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler, OneHotEncoder

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', RobustScaler())
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [53]:
preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_cols),
    ('cat', cat_pipeline, cat_cols),
    ('bool', 'passthrough', bool_cols)
])
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', RobustScaler())]),
                                 ['Price', 'Size_MB', 'Min_Android',
                                  'Released_Year', 'Last_Updated_Year']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Category', 'Content Rating']),
                                ('bool', 'passthrough',
                                 ['Free', 'Ad Supported', 'In App Purchases'])])

-Machine Trainning

In [54]:
#%pip install xgboost

1.Logistic Regression

In [55]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LogisticRegression(max_iter=1000, class_weight='balanced'))
])
lr_pipe.fit(X_train, y_train)
y_pred_lr = lr_pipe.predict(X_test)
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.83      0.90     38709
           1       0.14      0.80      0.23      1291

    accuracy                           0.83     40000
   macro avg       0.56      0.81      0.57     40000
weighted avg       0.96      0.83      0.88     40000

In [56]:
from sklearn.metrics import accuracy_score

y_train_pred_lr = lr_pipe.predict(X_train)
print("Train Accuracy:", accuracy_score(y_train, y_train_pred_lr))
print("Test Accuracy:", accuracy_score(y_test, y_pred_lr))

Train Accuracy: 0.8297625
Test Accuracy: 0.83015

2.Decision Tree

In [57]:
from sklearn.tree import DecisionTreeClassifier

dt_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', DecisionTreeClassifier(max_depth=10, class_weight='balanced', random_state=42))
])
dt_pipe.fit(X_train, y_train)
y_pred_dt = dt_pipe.predict(X_test)
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.99      0.81      0.89     38709
           1       0.12      0.81      0.21      1291

    accuracy                           0.81     40000
   macro avg       0.56      0.81      0.55     40000
weighted avg       0.96      0.81      0.87     40000

In [58]:
y_train_pred_dt = dt_pipe.predict(X_train)
print("Train Accuracy:", accuracy_score(y_train, y_train_pred_dt))
print("Test Accuracy:", accuracy_score(y_test, y_pred_dt))

Train Accuracy: 0.80723125
Test Accuracy: 0.8054

3.Random Forest

In [59]:
from sklearn.ensemble import RandomForestClassifier

rf_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestClassifier(n_estimators=100, max_depth=15, class_weight='balanced', n_jobs=-1, random_state=42))
])
rf_pipe.fit(X_train, y_train)
y_pred_rf = rf_pipe.predict(X_test)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.99      0.88      0.93     38709
           1       0.17      0.76      0.28      1291

    accuracy                           0.87     40000
   macro avg       0.58      0.82      0.61     40000
weighted avg       0.96      0.87      0.91     40000

In [60]:
y_train_pred_rf = rf_pipe.predict(X_train)
print("Train Accuracy:", accuracy_score(y_train, y_train_pred_rf))
print("Test Accuracy:", accuracy_score(y_test, y_pred_rf))

Train Accuracy: 0.8790125
Test Accuracy: 0.8734

In [61]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'model__n_estimators': [100, 200],
    'model__max_depth': [10, 15, 20]
}

grid = GridSearchCV(rf_pipe, param_grid, cv=3, scoring='f1', n_jobs=-1)
grid.fit(X_train, y_train)

print("Best parameters:", grid.best_params_)
print("Best F1 (CV):", grid.best_score_)

Best parameters: {'model__max_depth': 20, 'model__n_estimators': 200}
Best F1 (CV): 0.31234824467057737

In [62]:
best_rf = grid.best_estimator_
y_pred_best = best_rf.predict(X_test)
print(classification_report(y_test, y_pred_best))

              precision    recall  f1-score   support

           0       0.99      0.91      0.95     38709
           1       0.20      0.68      0.31      1291

    accuracy                           0.90     40000
   macro avg       0.60      0.80      0.63     40000
weighted avg       0.96      0.90      0.93     40000

In [63]:
y_train_pred_best = best_rf.predict(X_train)
print("Train Accuracy:", accuracy_score(y_train, y_train_pred_best))
print("Test Accuracy:", accuracy_score(y_test, y_pred_best))

Train Accuracy: 0.91934375
Test Accuracy: 0.903875

In [64]:
from sklearn.metrics import precision_score, recall_score

y_prob_best = best_rf.predict_proba(X_test)[:, 1]

for t in [0.5, 0.6, 0.7, 0.8, 0.9]:
    y_pred_t = (y_prob_best >= t).astype(int)
    print("Threshold:", t,
          "| Precision:", round(precision_score(y_test, y_pred_t), 2),
          "| Recall:", round(recall_score(y_test, y_pred_t), 2))

Threshold: 0.5 | Precision: 0.2 | Recall: 0.68
Threshold: 0.6 | Precision: 0.27 | Recall: 0.57
Threshold: 0.7 | Precision: 0.34 | Recall: 0.42
Threshold: 0.8 | Precision: 0.45 | Recall: 0.26
Threshold: 0.9 | Precision: 0.54 | Recall: 0.1

In [65]:
from sklearn.metrics import confusion_matrix

final_threshold = 0.7
y_pred_final = (y_prob_best >= final_threshold).astype(int)

print(classification_report(y_test, y_pred_final))
print(confusion_matrix(y_test, y_pred_final))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98     38709
           1       0.34      0.42      0.37      1291

    accuracy                           0.95     40000
   macro avg       0.66      0.70      0.68     40000
weighted avg       0.96      0.95      0.96     40000

[[37651  1058]
 [  749   542]]

To save the model

In [66]:

import joblib
joblib.dump(best_rf, 'final_model.pkl', compress=3)
joblib.dump(best_rf.named_steps['preprocessor'], 'preprocessor.pkl')
joblib.dump(final_threshold, 'threshold.pkl')

print("Saved ✅")

Saved ✅

Now we will discover what is the most columns that the model take the action according to it.(Feature Selection)

In [69]:
px.bar(importance_df.head(15), x='Importance', y='Feature', orientation='h',
       title='Top 15 Most Important Features')

In [87]:
%pip install streamlit

Requirement already satisfied: streamlit in c:\My anaconda\envs\honda\Lib\site-packages (1.60.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (3.1.56)
Requirement already satisfied: numpy<3,>=1.23 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (2.4.4)
Requirement already satisfied: packaging>=20 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (3.0.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (12.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=3.20 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (7.35.1)
Requirement already satisfied: pyarrow<25,>=7.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette<2,>=0.40.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn<1,>=0.30.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (0.51.0)
Requirement already satisfied: httptools<1,>=0.6.3 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (16.1.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\My anaconda\envs\honda\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\My anaconda\envs\honda\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\My anaconda\envs\honda\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\My anaconda\envs\honda\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in c:\My anaconda\envs\honda\Lib\site-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: colorama in c:\My anaconda\envs\honda\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\My anaconda\envs\honda\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\My anaconda\envs\honda\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\My anaconda\envs\honda\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\My anaconda\envs\honda\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\My anaconda\envs\honda\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in c:\My anaconda\envs\honda\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\My anaconda\envs\honda\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Requirement already satisfied: h11>=0.8 in c:\My anaconda\envs\honda\Lib\site-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\My anaconda\envs\honda\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\My anaconda\envs\honda\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\My anaconda\envs\honda\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\My anaconda\envs\honda\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\My anaconda\envs\honda\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in c:\My anaconda\envs\honda\Lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Note: you may need to restart the kernel to use updated packages.